language: java

jdk:
#  - openjdk8
  - oraclejdk8

env:
  - MAVEN=3.5.0

cache:
  directories:
    - $HOME/.m2


before_install:
  - gpg --keyserver pgp.mit.edu --recv-key ${FREKELE_GPGKEY}
  - export MVN_HOME=/tmp/maven-${MAVEN}
  - mkdir ${MVN_HOME}
  - export PATH=${MVN_HOME}/bin:$PATH


install:
  - wget -qO- https://archive.apache.org/dist/maven/maven-3/${MAVEN}/binaries/apache-maven-${MAVEN}-bin.tar.gz | tar xz --strip 1 -C ${MVN_HOME}


before_script:


script:
  - ${MVN_HOME}/bin/mvn --settings .travis/settings.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -V


before_cache:


after_success:
  - bash <(curl -s https://codecov.io/bash)


after_failure:


before_deploy:


deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      tags: true
      jdk: oraclejdk8

  
after_deploy:


after_script:
